# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
  profile: assertive
  high_level_summary: true
  changed_files_summary: false
  sequence_diagrams: false
  poem: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: ['Crowdin']
    labels: []
    drafts: false
    base_branches: []
  tools:
    ruff:
      enabled: false
    github-checks:
      enabled: true
      timeout_ms: 360000
    biome:
      enabled: true
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: false
    detekt:
      enabled: false
    flake8:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    pmd:
      enabled: false
    cppcheck:
      enabled: false
    circleci:
      enabled: false
    clippy:
      enabled: false
    sqlfluff:
      enabled: false
    pylint:
      enabled: false
    oxc:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    checkmake:
      enabled: false
