tasks:
  - name: Start
    init: |
      cp .env.example .env &&
      sed -i 's@^VITE_FRONTEND_URL=.*@VITE_FRONTEND_URL='"$(gp url 5000)"'@g' .env
      sed -i 's@^VITE_BACKEND_URL=.*@VITE_BACKEND_URL='"$(gp url 8000)"'@g' .env
    command: docker compose up

ports:
  - name: frontend
    port: 5000
    visibility: public
  - name: backend
    port: 8000
    visibility: public
  - name: inbucket
    port: 9000
  - name: mongo-express
    port: 8081

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - esbenp.prettier-vscode
    - streetsidesoftware.code-spell-checker
    - vue.volar
