services:
  backend:
    image: davidloe/abrechnung-backend
    restart: always
    depends_on:
      - db
    # volumes:
    # - ./reports/travel:/reports/travel #BACKEND_SAVE_REPORTS_ON_DISK
    # - ./reports/expenseReport:/reports/expenseReport #BACKEND_SAVE_REPORTS_ON_DISK
    # - ./reports/advance:/reports/advance #BACKEND_SAVE_REPORTS_ON_DISK
    # - ./reports/healthCareCost:/reports/healthCareCost #BACKEND_SAVE_REPORTS_ON_DISK
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file:
      - .env

  frontend:
    image: davidloe/abrechnung-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:80
    env_file:
      - .env

  db:
    image: mongo
    restart: always
    volumes:
      - db_data:/data/db

volumes:
  db_data:
