name: Code quality

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          working-dir: backend
          version: 1.9.4
      - name: Run Biome
        run: biome ci --changed .
