name: Code quality

on:
  workflow_call:

jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          working-dir: backend
          version: 1.9.4
      - name: Run Biome
        run: biome ci --changed --no-errors-on-unmatched .
